services:
  db:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: job-tracker-db
    volumes:
      - db-data:/var/lib/postgresql/data
    expose:
      - "5432"

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./api/.env.production
    depends_on:
      - db
    expose:
      - "3001"

  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./web/.env.production
    expose:
      - "3000"
    depends_on:
      - backend

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend

volumes:
  db-data:

networks:
  default:
    name: job-tracker-network